version: "3.1"

services:
  frontend:
    build:
      context: ../../
      dockerfile: deploy/app/Dockerfile-frontend
    restart: always
    ports:
      - 5000:5000

  api:
    build: 
      context: ../../
      dockerfile: deploy/app/Dockerfile-api
    restart: always
    ports:
      - 9000:9000

